### Same procedure as notebook.ipynb but with validation data to fine tune thresholds

In [15]:
import pandas as pd
df = pd.read_csv("data/german.data-numeric", sep=r"\s+", header = None)

In [16]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=24)
y = df[24]

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=42, test_size=0.2, stratify=y)

Creating a split from train data, into validation and train data

In [18]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, stratify=y_train, random_state=42, test_size = 0.25)

### Scale the data
`fit_transform()` only for training data rest only `transform`

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_val_scaled = scaler.transform(x_val)
x_test_scaled = scaler.transform(x_test)

In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [21]:
y_pred = model.predict(x_val_scaled)
y_pred

array([1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 2])

In [22]:
y_pred_proba = model.predict_proba(x_val_scaled)
y_pred_proba

array([[0.92568225, 0.07431775],
       [0.62191152, 0.37808848],
       [0.94503241, 0.05496759],
       [0.97319462, 0.02680538],
       [0.23679105, 0.76320895],
       [0.64223014, 0.35776986],
       [0.29316365, 0.70683635],
       [0.63186873, 0.36813127],
       [0.84828727, 0.15171273],
       [0.68467619, 0.31532381],
       [0.47988771, 0.52011229],
       [0.46428512, 0.53571488],
       [0.33275043, 0.66724957],
       [0.61617894, 0.38382106],
       [0.70674375, 0.29325625],
       [0.96293813, 0.03706187],
       [0.83620876, 0.16379124],
       [0.81603184, 0.18396816],
       [0.85799664, 0.14200336],
       [0.96486465, 0.03513535],
       [0.37737293, 0.62262707],
       [0.74391207, 0.25608793],
       [0.73259248, 0.26740752],
       [0.33749551, 0.66250449],
       [0.84348776, 0.15651224],
       [0.84088455, 0.15911545],
       [0.95865738, 0.04134262],
       [0.97552907, 0.02447093],
       [0.33197047, 0.66802953],
       [0.96091999, 0.03908001],
       [0.

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_val, y_pred)

cm

array([[119,  21],
       [ 38,  22]])

In [24]:
FP = cm[0, 1]
FN = cm[1, 0]
cost = FP * 1 + FN * 5

print("FP:", FP)
print("FN:", FN)
print("Cost:", cost)

FP: 21
FN: 38
Cost: 211


# Check thresholds
On validation data this time instead of directly on test data

In [25]:
import numpy as np 

for threshold in np.arange(0.1, 1.0, 0.1):
    y_pred_threshold = np.where(
        y_pred_proba[:,1] >= threshold, 2, 1
    )

    cm = confusion_matrix(y_val, y_pred_threshold)

    fp = cm[0, 1]
    fn = cm[1, 0]

    cost = fp * 1 + fn * 5

    print(f"Threshold: {threshold:.1f} | FP: {fp} | FN: {fn} | Cost: {cost}")

Threshold: 0.1 | FP: 98 | FN: 2 | Cost: 108
Threshold: 0.2 | FP: 65 | FN: 9 | Cost: 110
Threshold: 0.3 | FP: 48 | FN: 20 | Cost: 148
Threshold: 0.4 | FP: 28 | FN: 25 | Cost: 153
Threshold: 0.5 | FP: 21 | FN: 38 | Cost: 211
Threshold: 0.6 | FP: 17 | FN: 43 | Cost: 232
Threshold: 0.7 | FP: 9 | FN: 52 | Cost: 269
Threshold: 0.8 | FP: 2 | FN: 54 | Cost: 272
Threshold: 0.9 | FP: 0 | FN: 58 | Cost: 290


In [26]:
test_probabilities = model.predict_proba(x_test_scaled)[:,1]
test_probabilities

array([0.18915558, 0.09227768, 0.40084811, 0.68107627, 0.22492205,
       0.12280363, 0.12930004, 0.16458221, 0.56620184, 0.19187274,
       0.14971931, 0.4588394 , 0.04419348, 0.32471371, 0.43742373,
       0.07650343, 0.1838259 , 0.0856812 , 0.1803174 , 0.03727016,
       0.08450384, 0.2075925 , 0.11055732, 0.66056131, 0.38092398,
       0.39407575, 0.02226805, 0.25385975, 0.07740913, 0.03427656,
       0.22195594, 0.25088233, 0.15697093, 0.67992738, 0.16239346,
       0.78495718, 0.53419488, 0.87633474, 0.3217602 , 0.95410888,
       0.4604018 , 0.5225185 , 0.23394918, 0.42612031, 0.06509114,
       0.01992797, 0.69504369, 0.87094747, 0.23158555, 0.04116306,
       0.07912991, 0.10792455, 0.27380932, 0.59538867, 0.59785469,
       0.07159431, 0.0431022 , 0.07913457, 0.38546158, 0.58522248,
       0.17628533, 0.78735109, 0.30937014, 0.83839997, 0.10637963,
       0.1667132 , 0.02403988, 0.06653352, 0.83207112, 0.63889287,
       0.18869072, 0.5360825 , 0.06435496, 0.10933887, 0.26134

### Moving on with the picked threshold (0.1)

In [27]:
final_test_preds = np.where(test_probabilities >= 0.1, 2, 1)
cm_test = confusion_matrix(y_test, final_test_preds)
cm_test

array([[45, 95],
       [ 4, 56]])

In [28]:
fp_test = cm_test[0, 1]
fn_test = cm_test[1, 0]
final_cost = fp_test * 1 + fn_test * 5

print(f"Final Exam Cost: {final_cost}")
print(f"False Positives: {fp_test}")
print(f"False Negatives: {fn_test}")

Final Exam Cost: 115
False Positives: 95
False Negatives: 4
