# Load Data and inspect the elements with pandas

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("data/german.data-numeric", sep=r"\s+", header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1,6,4,12,5,5,3,4,1,67,...,0,0,1,0,0,1,0,0,1,1
1,2,48,2,60,1,3,2,2,1,22,...,0,0,1,0,0,1,0,0,1,2
2,4,12,4,21,1,4,3,3,1,49,...,0,0,1,0,0,1,0,1,0,1
3,1,42,2,79,1,4,3,4,2,45,...,0,0,0,0,0,0,0,0,1,1
4,1,24,3,49,1,3,3,4,4,53,...,1,0,1,0,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4,12,2,17,1,4,2,4,1,31,...,0,0,1,0,0,1,0,1,0,1
996,1,30,2,39,1,3,1,4,2,40,...,0,1,1,0,0,1,0,0,0,1
997,4,12,2,8,1,5,3,4,3,38,...,0,0,1,0,0,1,0,0,1,1
998,1,45,2,18,1,3,3,4,4,23,...,0,0,1,0,0,0,0,0,1,2


### Check for any null entries, number of rows and columns, data type of every column

In [28]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
dtype: int64

In [29]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1000 non-null   int64
 1   1       1000 non-null   int64
 2   2       1000 non-null   int64
 3   3       1000 non-null   int64
 4   4       1000 non-null   int64
 5   5       1000 non-null   int64
 6   6       1000 non-null   int64
 7   7       1000 non-null   int64
 8   8       1000 non-null   int64
 9   9       1000 non-null   int64
 10  10      1000 non-null   int64
 11  11      1000 non-null   int64
 12  12      1000 non-null   int64
 13  13      1000 non-null   int64
 14  14      1000 non-null   int64
 15  15      1000 non-null   int64
 16  16      1000 non-null   int64
 17  17      1000 non-null   int64
 18  18      1000 non-null   int64
 19  19      1000 non-null   int64
 20  20      1000 non-null   int64
 21  21      1000 non-null   int64
 22  22      1000 non-null   int64
 23  23      1000 non-null   i

(1000, 25)

### Check the distribution in the 24th column i.e the actual good vs bad determiner
From the below cell we can see that 70% of applicants are Good = 1 and 30% are Bad = 2

In [30]:
df[24].value_counts()

24
1    700
2    300
Name: count, dtype: int64

# Import from skikitlearn and train_test_split the data

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
# X has only the attributes that define good and bad
# Y has the values that decide whether applicant is good or bad

X = df.drop(columns=24)
Y = df[24]

### Train and Inspect
Split the data into 80-20, 80% is used to train your model whereas 20% to test your model (test_size=0.2), also maintain the ratio of good to bad within the test and train data (stratify=Y), can ensure reproduceability using a random seed (random_state=42)

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [34]:
print(X_train.shape)
print(X_test.shape)

(800, 24)
(200, 24)


We can see that the training data is 80% of the original data and that test data is 70% of the original data

In [35]:
print(Y_train.value_counts())
print(Y_test.value_counts())

24
1    560
2    240
Name: count, dtype: int64
24
1    140
2     60
Name: count, dtype: int64


We can see that the train and test data have split in proper proportions of 7:3 w.r.t the original proportions of the data

## Scale the data
Use StandardScaler to scale data of varying ranges into a understandable and simple range (0-1) and apply it with `.fit` and `.fit_transform` the former for test attributes and the latter for trian attributes.

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [37]:
# Check out the scaled data for reference

print(X_train_scaled.shape)
print(X_test_scaled.shape)
print(X_train_scaled[:2])

(800, 24)
(200, 24)
[[-1.25654318  1.28959203 -0.5163994   1.91106434  1.83848692  1.33571746
   0.43601168  1.05341302  1.55875081  1.05778394  0.46460993 -0.71874547
  -0.43643578 -0.82717019 -0.20077872 -0.5658021   2.91955639  0.31207962
  -0.21068086 -0.46852129 -1.5742493  -0.14285714 -0.49609064  0.75203572]
 [ 1.1292983  -0.74259502 -0.5163994  -0.89327582 -0.70723275  1.33571746
   0.43601168  1.05341302  0.60684192  0.24244893  0.46460993 -0.71874547
  -0.43643578 -0.82717019 -0.20077872 -0.5658021  -0.34251779  0.31207962
  -0.21068086 -0.46852129  0.6352234  -0.14285714 -0.49609064  0.75203572]]


# Choose a model and fit it to your data
Logistic Regression here is used because we are trying to predict the class of applicants (Good or Bad), it predicts the probablity of good or bad and assigns a class to each row

In [38]:
from sklearn.linear_model import LogisticRegression

# set the model to LogisticRegression
model = LogisticRegression()

# Train the model on train data X_train and its results Y_train
model.fit(X_train_scaled, Y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

Now that the model is trained test on your test_data to check how it performs
use the `.predict` function on scaled X_test data to check the results

In [39]:
y_pred = model.predict(X_test_scaled)

In [40]:
print(y_pred[:20])
print(Y_test.iloc[:20].values)

[1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1]
[1 1 2 1 2 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1]


We can see here that the predicted data is a little varying to the actual outcomes that shouldve come

# Check out the metrics
Check out the accuracy of the model the confusion matrix, precision, recall and F1

In [41]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, y_pred)

print(accuracy)

0.77


In [42]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred)

print(cm)

# Use this to get the TP, TN, FP, FN
# here it is 29, 125, 15, 31 respectively

[[125  15]
 [ 31  29]]


In [43]:
from sklearn.metrics import precision_score, recall_score

precision = precision_score(Y_test, y_pred, pos_label=2)
recall = recall_score(Y_test, y_pred, pos_label=2)

print("Precision:", precision)
print("Recall:", recall)

Precision: 0.6590909090909091
Recall: 0.48333333333333334


In [44]:
from sklearn.metrics import f1_score

f1 = f1_score(Y_test, y_pred, pos_label=2)

print("F1:", f1)

F1: 0.5576923076923077


### Check the probability of good and bad for each applicant in the data

0th Column - Probability of Good

1st Column - Probability of Bad

In [45]:
y_proba = model.predict_proba(X_test_scaled)
print(y_proba)
print(model.classes_)

[[0.80648142 0.19351858]
 [0.87860268 0.12139732]
 [0.57969442 0.42030558]
 [0.32592607 0.67407393]
 [0.81031593 0.18968407]
 [0.90983455 0.09016545]
 [0.85743009 0.14256991]
 [0.8221753  0.1778247 ]
 [0.48662112 0.51337888]
 [0.79333225 0.20666775]
 [0.85306425 0.14693575]
 [0.52933695 0.47066305]
 [0.9497809  0.0502191 ]
 [0.61330739 0.38669261]
 [0.54610656 0.45389344]
 [0.92729763 0.07270237]
 [0.71475465 0.28524535]
 [0.91207365 0.08792635]
 [0.818685   0.181315  ]
 [0.94637241 0.05362759]
 [0.87894095 0.12105905]
 [0.77249609 0.22750391]
 [0.86196277 0.13803723]
 [0.38490492 0.61509508]
 [0.78930115 0.21069885]
 [0.53343009 0.46656991]
 [0.97944582 0.02055418]
 [0.71758834 0.28241166]
 [0.85679492 0.14320508]
 [0.97383974 0.02616026]
 [0.85702615 0.14297385]
 [0.75221404 0.24778596]
 [0.83872205 0.16127795]
 [0.34335279 0.65664721]
 [0.80527085 0.19472915]
 [0.30941103 0.69058897]
 [0.48492458 0.51507542]
 [0.13355735 0.86644265]
 [0.65311691 0.34688309]
 [0.09114169 0.90885831]


In [46]:
bad_probability = model.predict_proba(X_test_scaled)[:, 1]
bad_probability

array([0.19351858, 0.12139732, 0.42030558, 0.67407393, 0.18968407,
       0.09016545, 0.14256991, 0.1778247 , 0.51337888, 0.20666775,
       0.14693575, 0.47066305, 0.0502191 , 0.38669261, 0.45389344,
       0.07270237, 0.28524535, 0.08792635, 0.181315  , 0.05362759,
       0.12105905, 0.22750391, 0.13803723, 0.61509508, 0.21069885,
       0.46656991, 0.02055418, 0.28241166, 0.14320508, 0.02616026,
       0.14297385, 0.24778596, 0.16127795, 0.65664721, 0.19472915,
       0.69058897, 0.51507542, 0.86644265, 0.34688309, 0.90885831,
       0.52504295, 0.50354098, 0.17757488, 0.34802542, 0.07439098,
       0.026362  , 0.7587646 , 0.80722553, 0.16457545, 0.05547818,
       0.08314404, 0.13767252, 0.34442205, 0.58636537, 0.64154044,
       0.07982696, 0.04498891, 0.04739301, 0.34587686, 0.5782647 ,
       0.16420492, 0.76503198, 0.30785264, 0.72363468, 0.13472641,
       0.24010212, 0.02497082, 0.10310839, 0.68441738, 0.64220712,
       0.15487117, 0.48541012, 0.09424198, 0.09935672, 0.32452

# Check the precision and recall with different Thresholds

In [47]:
import numpy as np

threshold = 0.4
y_pred_04 = np.where(bad_probability >= threshold, 2,1)

In [48]:
precision_04 = precision_score(Y_test, y_pred_04, pos_label=2)
recall_04 = recall_score(Y_test, y_pred_04, pos_label=2)

print("Precision:", precision_04)
print("Recall:", recall_04)

Precision: 0.65625
Recall: 0.7


### Loop through each threshold from 0.1 to 1.0 and check the precision and recall

In [50]:
thresholds = np.arange(0.1, 1.0, 0.1)

for threshold in thresholds:
    y_pred_threshold = np.where(bad_probability >= threshold, 2, 1)

    precision = precision_score(Y_test, y_pred_threshold, pos_label=2)
    recall = recall_score(Y_test, y_pred_threshold, pos_label=2)

    print(
        f"Threshold: {threshold:.1f} | "
        f"Precision: {precision:.2f} | "
        f"Recall: {recall:.2f}"
    )

Threshold: 0.1 | Precision: 0.36 | Recall: 0.95
Threshold: 0.2 | Precision: 0.46 | Recall: 0.85
Threshold: 0.3 | Precision: 0.59 | Recall: 0.78
Threshold: 0.4 | Precision: 0.66 | Recall: 0.70
Threshold: 0.5 | Precision: 0.66 | Recall: 0.48
Threshold: 0.6 | Precision: 0.71 | Recall: 0.37
Threshold: 0.7 | Precision: 0.78 | Recall: 0.23
Threshold: 0.8 | Precision: 0.75 | Recall: 0.10
Threshold: 0.9 | Precision: 0.67 | Recall: 0.03


## Find the actual cost of FP and FN as both are not equal
A FN is worth 5 times a FP

In [53]:
cm = confusion_matrix(Y_test, y_pred_04)
FP = cm[0, 1]
FN = cm[1, 0]
print(cm)

[[118  22]
 [ 18  42]]


In [54]:
cost = FP * 1 + FN * 5

print("FP:", FP)
print("FN:", FN)
print("Cost:", cost)

FP: 22
FN: 18
Cost: 112


### Cost for each threshold in the test data

In [55]:
for threshold in thresholds:
    y_pred_threshold = np.where(
        bad_probability >= threshold, 2, 1
    )

    cm = confusion_matrix(Y_test, y_pred_threshold)

    fp = cm[0, 1]
    fn = cm[1, 0]

    cost = fp * 1 + fn * 5

    print(f"Threshold: {threshold:.1f} | FP: {fp} | FN: {fn} | Cost: {cost}")

Threshold: 0.1 | FP: 102 | FN: 3 | Cost: 117
Threshold: 0.2 | FP: 59 | FN: 9 | Cost: 104
Threshold: 0.3 | FP: 33 | FN: 13 | Cost: 98
Threshold: 0.4 | FP: 22 | FN: 18 | Cost: 112
Threshold: 0.5 | FP: 15 | FN: 31 | Cost: 170
Threshold: 0.6 | FP: 9 | FN: 38 | Cost: 199
Threshold: 0.7 | FP: 4 | FN: 46 | Cost: 234
Threshold: 0.8 | FP: 2 | FN: 54 | Cost: 272
Threshold: 0.9 | FP: 1 | FN: 58 | Cost: 291


### Conclusion
Since we tested the thresholds directly on the test data we cannot be sure that it might hold true for all of the credit data, therefore creating a validation data (splitting test data) would be a better approach while analysing threasholds, which is what we'll do in our other notebook, and even though threshold 0.3 is the least expensive we can't be for sure it is the right one.